---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      version: 1.14.3
      interval: 5m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: crossplane
  targetNamespace: crossplane 
